[options]
list_db = False
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
log_level = debug
log_handler = odoo.addons.auth_oauth:DEBUG
workers = 2
longpolling_port = 8072